name: Build Python Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile viewer.py

    - name: Prepare for zip
      run: |
        mkdir build/toZip
        ls
        cp dist/viewer.exe build/toZip/viewer.exe

    - name: Zip Docs and Build
      uses: TheDoctor0/zip-release@0.7.6
      with:
       directory: build/toZip # File to add to the archive
       path: ./*
       Filename: viewer.zip # The name of the archive file

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/toZip/viewer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
